#ifndef COIN_ENCODINGS_H
#define COIN_ENCODINGS_H

#define C3K_STUDY_BASE58_CHARS "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"

#define DEFAULT_BASE58_CHARS C3K_STUDY_BASE58_CHARS

#endif // COIN_ENCODINGS_H
